name: recipe_hub
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  smooth_page_indicator: ^1.1.0
  flutter_localizations:
    sdk: flutter
  uuid: ^4.3.3
  dotted_border: ^2.0.0+3
  image_picker: ^1.0.4
  flutter_spinkit: ^5.2.0
  flutter_rating_bar: ^4.0.1
  share_plus: ^7.2.2
  fancy_shimmer_image: ^2.0.3
  card_swiper: ^3.0.1
  persistent_bottom_nav_bar_v2: ^4.2.8
  cloud_firestore: ^4.15.8
  firebase_messaging: ^14.7.19
  firebase_core: ^2.24.2
  firebase_auth: ^4.17.8
  firebase_storage: ^11.6.9
  flutter_local_notifications: ^17.0.0
  dartz: ^0.10.1
  iconly: ^1.0.1
  get_it: ^7.6.7
  shimmer: ^3.0.0
  equatable: ^2.0.5
  flutter_svg: ^2.0.10+1
  google_fonts: ^6.2.1
  flutter_hooks: ^0.20.5
  json_annotation: ^4.8.1
  flutter_riverpod: ^2.5.1
  connectivity_plus: ^5.0.2
  hooks_riverpod: ^2.5.1
  shared_preferences: ^2.2.2
  riverpod_annotation: ^2.3.5
  cached_network_image: ^3.3.1
  top_snackbar_flutter: ^3.1.0
  http: ^1.2.0
  loading_indicator: ^3.1.1
  intl: any
  duration_picker: ^1.1.1
  freezed_annotation: ^2.4.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  custom_lint: ^0.6.0
  build_runner: ^2.4.7
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  flutter_lints: ^3.0.1


flutter:
  generate: true

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/static/
    - assets/svgs/
